### ISSUE TITLE
YAM Misformatting

### ISSUE THREAD

**Issue by amouat** [chainguard-dev/yam#20]
I'm working on vault.yaml and it had the following:

```
...
      install -m755 -d "${{targets.destdir}}/var/log/vault"

  - uses: strip

    # Apparently caps have to be set after strip!
  - runs: setcap cap_ipc_lock=+ep "${{targets.destdir}}/usr/bin/vault"
...
```

YAM formatted this as:

```
      install -m755 -d "${{targets.destdir}}/var/log/vault"

  - uses
    # Apparently caps have to be set after strip!: strip

  - runs: setcap cap_ipc_lock=+ep "${{targets.destdir}}/usr/bin/vault"
```

Which breaks things :/

**Comment by luhring** [comment]
Yeah, there's a few edge cases in the YAML library like this, e.g. https://github.com/go-yaml/yaml/issues/587 😞 

Part of the problem here too is that it looks like your comment is indented one time too many, which signals your intent as wanting the comment to be associated with the _content_ of the list item _above_ (i.e. `uses: strip`).

But I'm guessing you meant for it to be a comment for the _below_ list item itself:

```
...
      install -m755 -d "${{targets.destdir}}/var/log/vault"

  - uses: strip

  # Apparently caps have to be set after strip!
  - runs: setcap cap_ipc_lock=+ep "${{targets.destdir}}/usr/bin/vault"
...
```
